#!/bin/bash

VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout=true)
echo "POM Version: $VERSION"

echo "------ HOOK START - BUILD -------"

docker build --build-arg giturl=https://github.com/MaheshIare/docker-demo-repo.git\
  --build-arg projectname=$PROJECT_NAME\
  --build-arg artifactid=$ARTIFACT_ID\
  --build-arg version=$VERSION\
  -t maheshiare/$PROJECT_NAME - < Dockerfile


echo "Branch: ${SOURCE_BRANCH}"
echo "Commit id: ${SOURCE_COMMIT}"
echo "Commit message: ${COMMIT_MSG}"
echo "Docker repo: ${DOCKER_REPO}"
echo "Docker file path: ${DOCKERFILE_PATH}"
echo "Docker tag: ${DOCKER_TAG}"
echo "Docke image name: ${IMAGE_NAME}"
echo "Project name: ${PROJECT_NAME}"
echo "Artifact id: ${ARTIFACT_ID}"
echo "Version: ${VERSION}"
echo "------ HOOK END   - BUILD -------"